
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Insets;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shanice Vergonia
 */
public class Calculator extends javax.swing.JFrame {

    /**
     * Creates new form Calculator
     */
    public Calculator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        sevenB = new javax.swing.JButton();
        eightB = new javax.swing.JButton();
        nineB = new javax.swing.JButton();
        fourB = new javax.swing.JButton();
        fiveB = new javax.swing.JButton();
        sixB = new javax.swing.JButton();
        oneB = new javax.swing.JButton();
        twoB = new javax.swing.JButton();
        threeB = new javax.swing.JButton();
        zeroB = new javax.swing.JButton();
        eraseB = new javax.swing.JButton();
        and = new javax.swing.JButton();
        close = new javax.swing.JButton();
        or = new javax.swing.JButton();
        exor = new javax.swing.JButton();
        not = new javax.swing.JButton();
        equalsB = new javax.swing.JButton();
        del = new javax.swing.JButton();
        open = new javax.swing.JButton();
        tf = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        optionsMenu = new javax.swing.JMenu();
        BitwiseCalculator = new javax.swing.JMenuItem();
        exitbutton = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Scientific Calculator");
        setBounds(new java.awt.Rectangle(50, 50, 340, 500));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(26, 40, 63));
        jPanel1.setForeground(new java.awt.Color(26, 40, 63));
        jPanel1.setLayout(null);

        sevenB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/number7.png"))); // NOI18N
        sevenB.setBorderPainted(false);
        sevenB.setContentAreaFilled(false);
        sevenB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenBActionPerformed(evt);
            }
        });
        jPanel1.add(sevenB);
        sevenB.setBounds(10, 170, 50, 60);

        eightB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/number8.png"))); // NOI18N
        eightB.setBorderPainted(false);
        eightB.setContentAreaFilled(false);
        eightB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightBActionPerformed(evt);
            }
        });
        jPanel1.add(eightB);
        eightB.setBounds(60, 170, 50, 60);

        nineB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/number9.png"))); // NOI18N
        nineB.setBorderPainted(false);
        nineB.setContentAreaFilled(false);
        nineB.setMaximumSize(new java.awt.Dimension(267, 115));
        nineB.setMinimumSize(new java.awt.Dimension(267, 115));
        nineB.setPreferredSize(new java.awt.Dimension(267, 115));
        nineB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineBActionPerformed(evt);
            }
        });
        jPanel1.add(nineB);
        nineB.setBounds(120, 170, 50, 60);

        fourB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/number4.png"))); // NOI18N
        fourB.setBorderPainted(false);
        fourB.setContentAreaFilled(false);
        fourB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourBActionPerformed(evt);
            }
        });
        jPanel1.add(fourB);
        fourB.setBounds(10, 240, 40, 50);

        fiveB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/number5.png"))); // NOI18N
        fiveB.setBorderPainted(false);
        fiveB.setContentAreaFilled(false);
        fiveB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveBActionPerformed(evt);
            }
        });
        jPanel1.add(fiveB);
        fiveB.setBounds(60, 240, 50, 50);

        sixB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/number6.png"))); // NOI18N
        sixB.setBorderPainted(false);
        sixB.setContentAreaFilled(false);
        sixB.setMaximumSize(new java.awt.Dimension(267, 115));
        sixB.setMinimumSize(new java.awt.Dimension(267, 115));
        sixB.setPreferredSize(new java.awt.Dimension(267, 115));
        sixB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixBActionPerformed(evt);
            }
        });
        jPanel1.add(sixB);
        sixB.setBounds(110, 240, 70, 50);

        oneB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/number1.png"))); // NOI18N
        oneB.setBorderPainted(false);
        oneB.setContentAreaFilled(false);
        oneB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneBActionPerformed(evt);
            }
        });
        jPanel1.add(oneB);
        oneB.setBounds(10, 300, 50, 50);

        twoB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/number2.png"))); // NOI18N
        twoB.setBorderPainted(false);
        twoB.setContentAreaFilled(false);
        twoB.setMaximumSize(new java.awt.Dimension(267, 115));
        twoB.setMinimumSize(new java.awt.Dimension(267, 115));
        twoB.setPreferredSize(new java.awt.Dimension(267, 115));
        twoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoBActionPerformed(evt);
            }
        });
        jPanel1.add(twoB);
        twoB.setBounds(60, 300, 50, 50);

        threeB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/number3.png"))); // NOI18N
        threeB.setBorderPainted(false);
        threeB.setContentAreaFilled(false);
        threeB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeBActionPerformed(evt);
            }
        });
        jPanel1.add(threeB);
        threeB.setBounds(120, 300, 50, 50);

        zeroB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/number0.png"))); // NOI18N
        zeroB.setBorderPainted(false);
        zeroB.setContentAreaFilled(false);
        zeroB.setMaximumSize(new java.awt.Dimension(267, 115));
        zeroB.setMinimumSize(new java.awt.Dimension(267, 115));
        zeroB.setPreferredSize(new java.awt.Dimension(267, 115));
        zeroB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroBActionPerformed(evt);
            }
        });
        jPanel1.add(zeroB);
        zeroB.setBounds(60, 360, 50, 60);

        eraseB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cancell_1.png"))); // NOI18N
        eraseB.setBorderPainted(false);
        eraseB.setContentAreaFilled(false);
        eraseB.setMaximumSize(new java.awt.Dimension(267, 115));
        eraseB.setMinimumSize(new java.awt.Dimension(267, 115));
        eraseB.setPreferredSize(new java.awt.Dimension(267, 115));
        eraseB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eraseBActionPerformed(evt);
            }
        });
        jPanel1.add(eraseB);
        eraseB.setBounds(180, 140, 80, 50);

        and.setIcon(new javax.swing.ImageIcon(getClass().getResource("/and-and.png"))); // NOI18N
        and.setBorderPainted(false);
        and.setContentAreaFilled(false);
        and.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                andActionPerformed(evt);
            }
        });
        jPanel1.add(and);
        and.setBounds(180, 250, 80, 70);

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close.png"))); // NOI18N
        close.setBorderPainted(false);
        close.setContentAreaFilled(false);
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        jPanel1.add(close);
        close.setBounds(260, 200, 80, 50);

        or.setIcon(new javax.swing.ImageIcon(getClass().getResource("/or-or.png"))); // NOI18N
        or.setBorderPainted(false);
        or.setContentAreaFilled(false);
        or.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orActionPerformed(evt);
            }
        });
        jPanel1.add(or);
        or.setBounds(260, 250, 80, 70);

        exor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exor_1.png"))); // NOI18N
        exor.setBorderPainted(false);
        exor.setContentAreaFilled(false);
        exor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exorActionPerformed(evt);
            }
        });
        jPanel1.add(exor);
        exor.setBounds(260, 320, 80, 50);

        not.setIcon(new javax.swing.ImageIcon(getClass().getResource("/not.png"))); // NOI18N
        not.setBorderPainted(false);
        not.setContentAreaFilled(false);
        not.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notActionPerformed(evt);
            }
        });
        jPanel1.add(not);
        not.setBounds(180, 320, 80, 50);

        equalsB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/equalsborder.png"))); // NOI18N
        equalsB.setBorderPainted(false);
        equalsB.setContentAreaFilled(false);
        equalsB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equalsBActionPerformed(evt);
            }
        });
        jPanel1.add(equalsB);
        equalsB.setBounds(190, 370, 140, 80);

        del.setIcon(new javax.swing.ImageIcon(getClass().getResource("/del.png"))); // NOI18N
        del.setBorderPainted(false);
        del.setContentAreaFilled(false);
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });
        jPanel1.add(del);
        del.setBounds(260, 140, 80, 50);

        open.setIcon(new javax.swing.ImageIcon(getClass().getResource("/open.png"))); // NOI18N
        open.setBorderPainted(false);
        open.setContentAreaFilled(false);
        jPanel1.add(open);
        open.setBounds(180, 200, 80, 50);

        tf.setEditable(false);
        tf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tf.setForeground(new java.awt.Color(250, 250, 250));
        tf.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        tf.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tf.setOpaque(false);
        tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfActionPerformed(evt);
            }
        });
        jPanel1.add(tf);
        tf.setBounds(20, 20, 300, 70);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 339;
        gridBagConstraints.ipady = 466;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jPanel1, gridBagConstraints);

        optionsMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/open-menu.png"))); // NOI18N
        optionsMenu.setText("Bitwise Calculator");
        optionsMenu.setIconTextGap(8);

        BitwiseCalculator.setText("Bitwise Calculator");
        BitwiseCalculator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BitwiseCalculatorActionPerformed(evt);
            }
        });
        optionsMenu.add(BitwiseCalculator);

        exitbutton.setText("Exit");
        exitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbuttonActionPerformed(evt);
            }
        });
        optionsMenu.add(exitbutton);

        jMenuBar1.add(optionsMenu);

        setJMenuBar(jMenuBar1);

        getAccessibleContext().setAccessibleName("Bitwise Calculator");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nineBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nineBActionPerformed

    private void sixBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sixBActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_closeActionPerformed

    private void exorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exorActionPerformed

    private void fiveBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fiveBActionPerformed

    private void oneBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oneBActionPerformed

    private void twoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_twoBActionPerformed

    private void threeBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_threeBActionPerformed

    private void fourBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fourBActionPerformed

    private void sevenBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sevenBActionPerformed

    private void eightBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eightBActionPerformed

    private void andActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_andActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_andActionPerformed

    private void notActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notActionPerformed

    private void orActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orActionPerformed

    private void equalsBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equalsBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_equalsBActionPerformed

    private void BitwiseCalculatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BitwiseCalculatorActionPerformed
        Calculator simple = new Calculator();
        simple.setVisible(true);
        simple.setSize(370,520);
        simple.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_BitwiseCalculatorActionPerformed

    private void exitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbuttonActionPerformed
       if(evt.getSource() == exitbutton){
            int response = JOptionPane.showConfirmDialog(
                    rootPane,
                    "Do you want to exit the program?",
                    "Quit", 
                    JOptionPane.OK_CANCEL_OPTION,
                    JOptionPane.QUESTION_MESSAGE);
            if(response == 0){
                 this.dispose();
            }
        }
    }//GEN-LAST:event_exitbuttonActionPerformed

    private void zeroBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zeroBActionPerformed

    private void eraseBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eraseBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eraseBActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delActionPerformed

    private void tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Calculator().setLocationRelativeTo(null);
                new Calculator().setVisible(true);
            }
        });
    }
    private static class RoundedBorder implements Border{
        private int radius;
        RoundedBorder(int radius){
            this.radius = radius;
        }
        @Override
        public Insets getBorderInsets(Component c){
            return new Insets(this.radius+1, this.radius+1, this.radius+2, this.radius);
        }
        @Override
        public boolean isBorderOpaque(){
            return true;
        }
        @Override
        public void paintBorder(Component c, Graphics g, int x, int y, int width, int height){
            g.drawRoundRect(x,y,width-1, height-1, radius, radius);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BitwiseCalculator;
    private javax.swing.JButton and;
    private javax.swing.JButton close;
    private javax.swing.JButton del;
    private javax.swing.JButton eightB;
    private javax.swing.JButton equalsB;
    private javax.swing.JButton eraseB;
    private javax.swing.JMenuItem exitbutton;
    private javax.swing.JButton exor;
    private javax.swing.JButton fiveB;
    private javax.swing.JButton fourB;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton nineB;
    private javax.swing.JButton not;
    private javax.swing.JButton oneB;
    private javax.swing.JButton open;
    private javax.swing.JMenu optionsMenu;
    private javax.swing.JButton or;
    private javax.swing.JButton sevenB;
    private javax.swing.JButton sixB;
    private javax.swing.JTextField tf;
    private javax.swing.JButton threeB;
    private javax.swing.JButton twoB;
    private javax.swing.JButton zeroB;
    // End of variables declaration//GEN-END:variables
}
